### ISSUE TITLE
Fails to compile on OpenBSD

### ISSUE THREAD

**Issue by AaronM04** [dylni/process_control#3]
Hello, I got a compile failure trying to build this on OpenBSD -CURRENT, with rust 1.48 and process_control 3.0.1:

```
error[E0432]: unresolved import `libc::P_PID`
  --> /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/process_control-3.0.1/src/unix.rs:18:5
   |
18 | use libc::P_PID;
   |     ^^^^^^^^^^^ no `P_PID` in the root

error[E0432]: unresolved import `libc::WEXITED`
  --> /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/process_control-3.0.1/src/unix.rs:20:5
   |
20 | use libc::WEXITED;
   |     ^^^^^^-------
   |     |     |
   |     |     help: a similar name exists in the module: `WIFEXITED`
   |     no `WEXITED` in the root

error[E0432]: unresolved import `libc::WNOWAIT`
  --> /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/process_control-3.0.1/src/unix.rs:21:5
   |
21 | use libc::WNOWAIT;
   |     ^^^^^^^^^^^^^ no `WNOWAIT` in the root

error[E0432]: unresolved import `libc::WSTOPPED`
  --> /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/process_control-3.0.1/src/unix.rs:22:5
   |
22 | use libc::WSTOPPED;
   |     ^^^^^^--------
   |     |     |
   |     |     help: a similar name exists in the module: `WIFSTOPPED`
   |     no `WSTOPPED` in the root

   Compiling crossbeam-deque v0.8.0
error[E0425]: cannot find function `waitid` in crate `libc`
   --> /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/process_control-3.0.1/src/unix.rs:159:27
    |
159 |                       libc::waitid(
    |                             ^^^^^^ help: a function with a similar name exists: `waitpid`
    |
   ::: /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.84/src/unix/mod.rs:995:5
    |
995 | /     pub fn waitpid(
996 | |         pid: pid_t,
997 | |         status: *mut ::c_int,
998 | |         options: ::c_int,
999 | |     ) -> pid_t;
    | |_______________- similarly named function `waitpid` defined here

error: aborting due to 5 previous errors
```

How would I fix this? Thanks!

**Comment by dylni** [comment]
Unfortunately, I don't think OpenBSD can be supported. This crate makes a strong effort to not terminate the wrong process under any circumstance. To make that happen, `waitid` is called in careful combination with other syscalls. However, it's not implemented for this platform AFAICT.

Do you know an alternative to `waitid` that's OpenBSD-specific or have any other suggestions?

**Comment by AaronM04** [comment]
@dylni I'm not sure what exact functionality you're looking for in a `waitid` equivalent, but OpenBSD does have `wait3` and `wait4` which might be usable: http://man.openbsd.org/wait4

**Comment by dylni** [comment]
@AaronM04 I use it to wait on processes without letting them terminate. That's the purpose of the `WNOWAIT` flag, which I use here:
https://github.com/dylni/process_control/blob/56f388fe1ff494d6b5edc2e08b9c85c76e38edf6/src/unix.rs#L159-L164

Unfortunately, I don't see any way to do that with `wait3` or `wait4`.

If there's nothing equivalent, one option is to make `Timeout::terminating` a compile error for this target and add `Timeout::terminating_if_possible` to only terminate for other targets. Would that work for your use case? Long-running processes would never be killed on OpenBSD with that implementation.

The best option would be to find a platform-specific syscall for this platform, but I don't think one exists.

**Comment by AaronM04** [comment]
@dylni this is the use case I'm concerned with: https://github.com/starship/starship/blob/master/src/utils.rs#L288

If I understand you correctly, this would be a compile error, so no, it wouldn't work.

**Comment by dylni** [comment]
@AaronM04 I responded [at the starship repository](https://github.com/starship/starship/issues/2276#issuecomment-782735325).

**Comment by dylni** [comment]
I'm closing this, since one of the starship maintainers [indicated](https://github.com/starship/starship/issues/2276#issuecomment-782736552) that they're close to merging a fix for this issue. If further use cases arise for this platform to be supported, this can be reopened.

**Comment by AaronM04** [comment]
Thanks for looking into this! 😀

**Comment by dylni** [comment]
No problem! :grinning: I'm glad it'll have a favorable resolution.
