### ISSUE TITLE
Bump libc dependency to 0.2.98

### ISSUE THREAD

**Issue by mjturner** [dylni/process_control#6]
I'm in the process of packaging [Starship](https://github.com/starship/starship/) for NetBSD and recently ran into an issue similar to #4. It's been resolved in libc version 0.2.98 and process_control now works fine on NetBSD, at least for Starship's purposes.

Would it be possible to bump the libc dependency to version 0.2.98? This will make it a bit easier for us to build Starship on NetBSD as we'll no longer need to patch the build to do a local version override. Thanks!

**Comment by dylni** [comment]
Yes, if bumping the minimum version makes your build easier, I can absolutely make that change.

Do you need the minimum version to be 0.2.98? From that issue, 0.2.88 (and possibly 0.2.87) should have support as well. I would rather avoid bumping libc to the latest version if possible, to avoid breaking builds or forcing a version that may be unusable for a project.

**Comment by mjturner** [comment]
Great, thanks. 

Unfortunately the fix for NetBSD is only in 0.2.98 and later (see [#2265](https://github.com/rust-lang/libc/issues/2265)). I agree that bumping libc to the latest version does have some risk associated - I'd be happy if you want to hold off until the next release or the release after that, just to be safe. I can drop you a reminder if a few weeks, if that's ok?

**Comment by dylni** [comment]
Thanks for the offer, but I decided to publish version 3.1.0 with the updated requirement. Since none of the published reverse-dependencies of libc have a version that forbids 0.2.98 but allows 0.2, this should be pretty safe. Any crates deciding later to add a maximum version for libc can add a maximum version for process_control too.

**Comment by mjturner** [comment]
Brilliant, thanks!
