### ISSUE TITLE
build for Android failed

### ISSUE THREAD

**Issue by leleliu008** [dylni/process_control#9]
Android NDK: 23.1.7779620

![14](https://user-images.githubusercontent.com/3040852/148874238-be80e1b2-3070-466a-bddb-b5ca9c33c0e6.PNG)

I am not familiar with rust. maybe this helps: https://github.com/rust-lang/rust/issues/43163

**Comment by dylni** [comment]
Thank you for the issue. Can you include the output of this command in the same environment?

```
rustup show
```

You can remove the `rustup home:` line.

If rustup isn't installed, the `host:` line from this command would be less helpful but still useful:

```
cargo -V -v
```

**Comment by leleliu008** [comment]
**rustup show**:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/fpliu/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
1.56-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

aarch64-linux-android
armv7-linux-androideabi
i686-linux-android
x86_64-linux-android
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.56.1 (59eed8a2a 2021-11-01)
```

**cargo -V -v**:
```
cargo 1.56.0 (4ed5d137b 2021-10-04)
release: 1.56.0
commit-hash: 4ed5d137baff5eccf1bae5a7b2ae4b57efad4a7d
commit-date: 2021-10-04
```

**Comment by dylni** [comment]
I couldn't reproduce this error, but I would expect version 3.2.1 to fix it. Let me know if compilation is successful with the new version.

**Comment by leleliu008** [comment]
I have confired that new version works for me. Thank you for your help.

**Comment by dylni** [comment]
Thank you for checking and reporting this issue.
